name: Build and Push Docker Image

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Récupère le code source du repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.2'  # Ajuste selon la version que tu utilises

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
          pip install pytest

      - name: Run tests
        run: pytest tests/  # Remplace `tests/` par le dossier contenant tes tests unitaires
        env:
          ENVIRONMENT: testing
          GOOGLE_API_KEY_TEST: ${{ secrets.GOOGLE_API_KEY_TEST}}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY_TEST}}
          OPENAI_API_KEY_TEST: ${{ secrets.OPENAI_API_KEY_TEST}}
        

  build-and-push:
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    
    permissions:
      contents: read        # Accès en lecture au code source
      packages: write       # Accès en écriture aux packages
      actions: read    

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Récupère le code source du repo

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          owner=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$owner/places-api:latest .

      - name: Push Docker image to GHCR
        run: |
          owner=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/$owner/places-api:latest